CREATE TABLE tbl_book_caterogy
(
	ID int IDENTITY(1,1) PRIMARY KEY,
	NAME nvarchar(250) NOT NULL,
	DESCRIPTION text NULL
);


CREATE TABLE tbl_book
(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	NAME NVARCHAR(500) NOT NULL,
	DESCRIPTION TEXT NULL,
	PUBLISHED_DATE DATE,
	AUTHOR NVARCHAR(50),
	IS_AVAILABLE_TO_LEND BIT,
	CATEGORY_ID INT FOREIGN KEY REFERENCES tbl_book_caterogy(ID)
);

CREATE TABLE tbl_user
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	FULL_NAME NVARCHAR(30) NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL,
	PASSWORD BINARY(60) NOT NULL 
);

CREATE TABLE tbl_book_lend
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	BOOK_ID INT FOREIGN KEY REFERENCES tbl_book(ID),
	USER_ID INT FOREIGN KEY REFERENCES tbl_user(ID),
	BORROW_DATE DATE NOT NULL,
	RETURN_DATE DATE NULL
);


/********CREATE DATA*************************/

SET IDENTITY_INSERT tbl_book_caterogy ON

INSERT INTO tbl_book_caterogy(ID,NAME,DESCRIPTION) VALUES(1, 'Science Book',' This is the category for science book');
INSERT INTO tbl_book_caterogy(ID,NAME,DESCRIPTION) VALUES(2, 'Child Book',' This is the category for child book');

SET IDENTITY_INSERT tbl_book_caterogy OFF
