FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /app

COPY "src/Modules/SD2411.KPI2019.Module.Users/modules-info.json" "app/Modules/SD2411.KPI2019.Module.Users/"
COPY "src/Modules/SD2411.KPI2019.Module.Core/modules-info.json" "app/Modules/SD2411.KPI2019.Module.Core/"
COPY "src/Modules/SD2411.KPI2019.Module.Books/modules-info.json" "app/Modules/SD2411.KPI2019.Module.Books/"
COPY "src/Modules/SD2411.KPI2019.Module.BookLending/modules-info.json" "app/Modules/SD2411.KPI2019.Module.BookLending/"

#COPY ["src/SD2411.KPI2019.HostStandard/SD2411.KPI2019.HostStandard.csproj", "src/SD2411.KPI2019.HostStandard/"]
COPY . .
# RUN dotnet restore "src/Infrastructure/SD2411.KPI2019.Infrastructure/SD2411.KPI2019.Infrastructure.csproj"

# RUN dotnet build "src/Infrastructure/SD2411.KPI2019.Infrastructure/SD2411.KPI2019.Infrastructure.csproj" -c Release -o /app

RUN dotnet restore "src/SD2411.KPI2019.HostStandard/SD2411.KPI2019.HostStandard.csproj"


#RUN dotnet restore "src/Modules/*.csproj"

#RUN dotnet build "src/SD2411.KPI2019.HostStandard/SD2411.KPI2019.HostStandard.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "src/SD2411.KPI2019.HostStandard/SD2411.KPI2019.HostStandard.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "SD2411.KPI2019.HostStandard.dll"]