version: '3.4'

services:
  sd2411.api:
    build:
        context: .
        dockerfile: Dockerfile
    image: sieunhantanbao/sd2411-kpi2019-api-testing
    ports: 
      - 81:80
    restart: always
    command: bash -c "dotnet /app/SD2411.KPI2019.HostStandard.dll"
  sd2411.client:
    build:
        context: ./client
        dockerfile: Dockerfile
        args:
           - webapiurl=http://localhost:81/api
    image: sieunhantanbao/sd2411-kpi2019-client-testing
    ports:
      - 82:80
    restart: always