version: '3.4'

services:
  sd2411.api:
    build:
        context: ../../
        dockerfile: ./build_deploy/dockerfiles/BackendDockerfile
    image: sieunhantanbao/sd2411-kpi2019-api:latest
    container_name: sd2411-api
    ports: 
      - 81:80
    restart: unless-stopped
    volumes: 
        - ../environments/appsettings.json:/app/appsettings.json
    command: bash -c "dotnet /app/SD2411.KPI2019.HostStandard.dll"
  sd2411.client:
    build:
        context: ../../client/
        dockerfile: ../build_deploy/dockerfiles/ClientDockerfile
    image: sieunhantanbao/sd2411-kpi2019-client:latest
    container_name: sd2411-client
    depends_on: 
        - sd2411.api
    ports:
      - 82:80
    restart: always
    volumes:
        - ../environments/default.conf:/etc/nginx/conf.d/default.conf
        - ../environments/environment.js:/usr/share/nginx/html/assets/environment.js