version: '3.4'

services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:v1.7.3
    ports:
    - "3000:3000"
    - "5000:5000"
    networks:
    - tyk
    volumes:
    - ../tyk/conf/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
    depends_on:
    - tyk-redis
    - tyk-mongo
    restart: unless-stopped
  tyk-gateway:
    image: tykio/tyk-gateway:v2.6.2
    ports:
    - "8181:8181"
    networks:
    - tyk
    volumes:
    - ../tyk/conf/tyk.conf:/opt/tyk-gateway/tyk.conf
    - ../certs/wildcard.mycompany.vn.crt:/certs/wildcard.mycompany.vn.crt
    - ../certs/wildcard.mycompany.vn.key:/certs/wildcard.mycompany.vn.key
    depends_on:
    - tyk-redis
    restart: unless-stopped
  tyk-pump:
    image: tykio/tyk-pump-docker-pub:v0.5.4
    networks:
    - tyk
    depends_on:
    - tyk-redis
    - tyk-mongo
    - tyk-gateway
    restart: unless-stopped
  tyk-redis:
    image: redis:5.0.3
    ports:
    - "6379:6379"
    networks:
    - tyk
    restart: unless-stopped
  tyk-mongo:
    image: mongo:3.2
    command: ["mongod", "--smallfiles"]
    ports:
    - "27017:27017"
    networks:
    - tyk
    restart: unless-stopped

networks:
  tyk: