{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sd2411-kpi2019-api.serviceAccountName" . }}
  labels:
{{ include "sd2411-kpi2019-api.labels" . | indent 4 }}
{{- end -}}
